In [ ]:
#Section A: Data Structures & Control Structures
#1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
#5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
#6.	Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative


In [57]:
#1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
df=[1,2,3,4,5,6,7]  # Create a list of Integers 
df

[1, 2, 3, 4, 5, 6, 7]

In [58]:
type(df)  # checking data type

list

In [59]:
df.append(60)  #  append() - Add an element to the end of the list
df

[1, 2, 3, 4, 5, 6, 7, 60]

In [60]:
df.insert(2, 25)
df                # insert() - Insert an element at a specific index

[1, 2, 25, 3, 4, 5, 6, 7, 60]

In [61]:
df.extend([70, 80]) # extend() - Add elements from another iterable to the end of the list
df

[1, 2, 25, 3, 4, 5, 6, 7, 60, 70, 80]

In [62]:
df.remove(4) # remove() - Remove the first occurrence of a value
df

[1, 2, 25, 3, 5, 6, 7, 60, 70, 80]

In [63]:
df1= df.pop(3)  # pop() - Remove and return an element at a given index (or the last element if no index is specified)
df

[1, 2, 25, 5, 6, 7, 60, 70, 80]

In [64]:
df2= df.index(70)  #index() - Return the index of the first occurrence of a value
df2

7

In [65]:
df3 = df.count(7)  #count() - Return the number of occurrences of a value
df3

1

In [66]:
df.sort()   # sort() - Sort the list in ascending order
df

[1, 2, 5, 6, 7, 25, 60, 70, 80]

In [67]:
df.reverse()  # reverse() - Reverse the order of the list
df

[80, 70, 60, 25, 7, 6, 5, 2, 1]

In [68]:
df.clear()   # clear() - Remove all elements from the list
df

[]

In [69]:
#2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

std = ("sai", "chinni", "Karthi")
std

('sai', 'chinni', 'Karthi')

In [70]:
std[1] = "devi"
std   # Because of In Python, tuples are immutable, meaning once a tuple is created, you cannot modify, add, or remove its elements.

TypeError: 'tuple' object does not support item assignment

In [71]:
#3. Create a set of integers with some duplicate values. Print the set and explain the output.

num = {1, 2, 3, 2, 4, 3, 5, 1}
num

{1, 2, 3, 4, 5}

In [72]:
# A set in Python is an unordered collection of unique elements.

#When you add duplicate values (2, 3, 1 in this case), the set automatically removes duplicates and only stores unique values.

#The order of elements in the output may not match the order you typed, because sets are unordered

In [73]:
#4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

dict = {
    'name': 'Sree',
    'age': 30,                    ## Create a dictionary
    'city': 'Kadapa'
}
dict

{'name': 'Sree', 'age': 30, 'city': 'Kadapa'}

In [74]:
dict['age'] = 35            # Update the age 
dict

{'name': 'Sree', 'age': 35, 'city': 'Kadapa'}

In [75]:
dict['email'] = 'omsreesairam@gmail.com'       # Add a new key 'email'
dict

{'name': 'Sree',
 'age': 35,
 'city': 'Kadapa',
 'email': 'omsreesairam@gmail.com'}

In [76]:
#5.  Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age = 20
age                     # Take age as a variable

20

In [77]:
# Check if the person is eligible to vote
if age >= 18:
    print("You are eligible to vote.")                    
else:
    print("You are not eligible to vote yet.")    

You are eligible to vote.


In [78]:
# 6. Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'


marks = 75     # Given a 'marks' variable

# Determine and print the grade
if marks >= 90:
    print('A')
elif marks >= 75:
    print('B')
elif marks >= 50:
    print('C')
else:
    print('Fail')

B


In [79]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative
num1 = -5      # Given a number
num1

-5

In [80]:
# Check if the number is positive, zero, or negative
if num1 >= 0: 
    print("Its Positive")
    # Check if the positive number is also even
    if num1%2==0:
        print("Its Even")
    else:
        print("Its odd")
else:
    print("its negative")

its negative


In [81]:
#Section B: Numpy
#8.	Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
#10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


In [82]:
#8.	Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10

import numpy as np

In [94]:
scalar = np.array(5)   # Create a scalar using np.array(5)
s1

array([1, 2, 3, 4, 5])

In [95]:
scalar = np.array([1, 2, 3, 4, 5])  # A 1D array with values 1 to 5
scalar

array([1, 2, 3, 4, 5])

In [96]:
scalar2= np.array([[10, 20, 30], [40, 50, 60]]) #  A 2D array (2x3) with values from 10 to 60 in steps of 10
scalar2

array([[10, 20, 30],
       [40, 50, 60]])

In [93]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint()
arr = np.random.randint(0, 101, size=(4, 4))    # Generate 4x4 array with random integers between 0 and 100
print(arr)

[[ 97 100  64  21]
 [ 59  22  67  57]
 [ 42  79  66  43]
 [ 57  71  68  65]]


In [87]:
import pandas as pd

In [88]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])  #Step 1: Create a 3x3 NumPy array

In [89]:
dm = pd.DataFrame(arr, columns=['A', 'B', 'C']) # Step 2: Convert to DataFrame with column names
dm

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [90]:
#Section C: Exploring Pandas
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Use .info(), .describe()
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows


In [91]:
dc = pd.read_csv("dataset.csv") #import CSV file 
dc

Name  Age       City   Salary
0    Alice   25      Delhi  50000.0
1      Bob   30     Mumbai  60000.0
2  Charlie   35    Chennai  75000.0
3    David   40    Kolkata      NaN
4      Eva   28      Delhi  58000.0
5    Frank   32  Bangalore  62000.0
6    Grace   29  Hyderabad  72000.0
7   Hannah   41       Pune  80000.0
8      Ian   36      Delhi      NaN
9     Jack   28     Mumbai  58000.0

In [92]:
d1 = pd.DataFrame(dc) # Convert dictionary into a pandas DataFrame
d1

Name  Age       City   Salary
0    Alice   25      Delhi  50000.0
1      Bob   30     Mumbai  60000.0
2  Charlie   35    Chennai  75000.0
3    David   40    Kolkata      NaN
4      Eva   28      Delhi  58000.0
5    Frank   32  Bangalore  62000.0
6    Grace   29  Hyderabad  72000.0
7   Hannah   41       Pune  80000.0
8      Ian   36      Delhi      NaN
9     Jack   28     Mumbai  58000.0

In [48]:
dc.info()   #summary of dataset (data types, null values)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [49]:
dc.describe() #statistical summary (mean, std, min, max, etc. for numeric columns)

Age        Salary
count  10.000000     10.000000
mean   32.400000  64375.000000
std     5.399588   8993.052874
min    25.000000  50000.000000
25%    28.250000  58500.000000
50%    31.000000  63187.500000
75%    35.750000  70093.750000
max    41.000000  80000.000000

In [50]:
dc[['Name', 'City']]  #Column selectio

Name       City
0    Alice      Delhi
1      Bob     Mumbai
2  Charlie    Chennai
3    David    Kolkata
4      Eva      Delhi
5    Frank  Bangalore
6    Grace  Hyderabad
7   Hannah       Pune
8      Ian      Delhi
9     Jack     Mumbai

In [51]:
dc.drop(dc.columns[[2]],axis=1)  # Drop column

Name  Age   Salary
0    Alice   25  50000.0
1      Bob   30  60000.0
2  Charlie   35  75000.0
3    David   40  64375.0
4      Eva   28  58000.0
5    Frank   32  62000.0
6    Grace   29  72000.0
7   Hannah   41  80000.0
8      Ian   36  64375.0
9     Jack   28  58000.0

In [52]:
dc['Salary'] = dc['Salary'].fillna(dc['Salary'].mean())   #replaces NaN in Salary with mean salary
dc

Name  Age       City   Salary
0    Alice   25      Delhi  50000.0
1      Bob   30     Mumbai  60000.0
2  Charlie   35    Chennai  75000.0
3    David   40    Kolkata  64375.0
4      Eva   28      Delhi  58000.0
5    Frank   32  Bangalore  62000.0
6    Grace   29  Hyderabad  72000.0
7   Hannah   41       Pune  80000.0
8      Ian   36      Delhi  64375.0
9     Jack   28     Mumbai  58000.0

In [53]:
df_no_duplicates = dc.drop_duplicates() # Remove duplicates
dc

Name  Age       City   Salary
0    Alice   25      Delhi  50000.0
1      Bob   30     Mumbai  60000.0
2  Charlie   35    Chennai  75000.0
3    David   40    Kolkata  64375.0
4      Eva   28      Delhi  58000.0
5    Frank   32  Bangalore  62000.0
6    Grace   29  Hyderabad  72000.0
7   Hannah   41       Pune  80000.0
8      Ian   36      Delhi  64375.0
9     Jack   28     Mumbai  58000.0